"use client";

import { useRouter } from "next/navigation";
import { fieldClass, ModuleHeader, primaryButton, secondaryButton } from "@/components/ui/ModuleUi";
import { updateDemoData, useDemoData } from "@/features/demo/services/demo-repository";
import type { InternalRequest, Priority } from "@/features/demo/types/demo";

const requestTypes: InternalRequest["type"][] = ["Demande de planification", "Demande d’avance OF", "Demande qualité", "Demande maintenance", "Demande de sous-traitance", "Suggestion", "Autre"];
export function NewRequest() { const router = useRouter(); const data = useDemoData(); function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); let id = ""; updateDemoData((draft) => { id = `DEM-${String(draft.requests.length + 1).padStart(3, "0")}`; draft.requests.unshift({ id, type: String(form.get("type")) as InternalRequest["type"], title: String(form.get("title")), description: String(form.get("description")), requester: String(form.get("requester")), responsible: String(form.get("responsible")), status: "Reçue", priority: String(form.get("priority")) as Priority, createdAt: new Date().toISOString().slice(0, 10), dueDate: String(form.get("dueDate")), workOrderId: String(form.get("workOrderId")) || null, machineId: String(form.get("machineId")) || null, comments: [], history: [{ id: crypto.randomUUID(), date: new Date().toISOString(), author: "Daniel Mülverstedt", description: "Demande créée" }] }); }); router.push(`/suivi/${id}`); }
  return <div className="mx-auto max-w-4xl"><ModuleHeader eyebrow="Centre de demandes" title="Nouvelle demande" description="Décrivez le besoin et reliez-le, si nécessaire, à un OF ou une machine." /><form onSubmit={submit} className="mt-6 grid gap-4 rounded-2xl border border-[var(--app-border)] bg-white p-5 sm:grid-cols-2"><label className="text-sm font-medium">Type<select name="type" className={`${fieldClass} mt-1 w-full`}>{requestTypes.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-sm font-medium">Priorité<select name="priority" className={`${fieldClass} mt-1 w-full`}><option>Normale</option><option>Haute</option><option>Urgente</option><option>Bloquante</option></select></label><label className="text-sm font-medium sm:col-span-2">Titre<input required name="title" className={`${fieldClass} mt-1 w-full`} /></label><label className="text-sm font-medium sm:col-span-2">Description<textarea required name="description" className={`${fieldClass} mt-1 min-h-32 w-full py-3`} /></label><label className="text-sm font-medium">Demandeur<input required name="requester" className={`${fieldClass} mt-1 w-full`} /></label><label className="text-sm font-medium">Responsable<input required name="responsible" className={`${fieldClass} mt-1 w-full`} /></label><label className="text-sm font-medium">Échéance<input required type="date" name="dueDate" className={`${fieldClass} mt-1 w-full`} /></label><label className="text-sm font-medium">OF lié<select name="workOrderId" className={`${fieldClass} mt-1 w-full`}><option value="">Aucun</option>{data.workOrders.map((item) => <option key={item.id}>{item.id}</option>)}</select></label><label className="text-sm font-medium">Machine liée<select name="machineId" className={`${fieldClass} mt-1 w-full`}><option value="">Aucune</option>{data.machines.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><div className="flex items-end gap-2"><button className={primaryButton}>Créer</button><button type="button" className={secondaryButton} onClick={() => router.back()}>Annuler</button></div></form></div>; }
