"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { EmptyState, fieldClass, formatEuropeanDate, ModuleHeader, primaryButton, StatusPill } from "@/components/ui/ModuleUi";
import { useDemoData } from "@/features/demo/services/demo-repository";

export function RequestsModule() {
  const data = useDemoData(); const [search, setSearch] = useState(""); const [status, setStatus] = useState("Tous"); const [type, setType] = useState("Tous");
  const requests = useMemo(() => data.requests.filter((item) => `${item.id} ${item.title} ${item.description} ${item.requester}`.toLocaleLowerCase("fr").includes(search.toLocaleLowerCase("fr")) && (status === "Tous" || item.status === status) && (type === "Tous" || item.type === type)), [data.requests, search, status, type]);
  return <div className="mx-auto max-w-7xl"><ModuleHeader eyebrow="Suivi transversal" title="Centre de demandes" description="Centralisez, affectez et suivez les demandes internes sans échanges dispersés." actions={<Link className={primaryButton} href="/suivi/nouvelle">Nouvelle demande</Link>} /><section className="mt-6 grid gap-2 rounded-2xl border border-[var(--app-border)] bg-white p-4 sm:grid-cols-3"><input className={fieldClass} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Rechercher…" /><select className={fieldClass} value={status} onChange={(event) => setStatus(event.target.value)}><option>Tous</option>{["Reçue", "En analyse", "Acceptée", "Refusée", "Planifiée", "En cours", "Terminée"].map((item) => <option key={item}>{item}</option>)}</select><select className={fieldClass} value={type} onChange={(event) => setType(event.target.value)}><option>Tous</option>{[...new Set(data.requests.map((item) => item.type))].map((item) => <option key={item}>{item}</option>)}</select></section><div className="mt-5 grid gap-3">{requests.length ? requests.map((request) => <Link href={`/suivi/${request.id}`} key={request.id} className="rounded-2xl border border-[var(--app-border)] bg-white p-5 shadow-sm hover:bg-slate-50"><div className="flex flex-wrap justify-between gap-2"><div><span className="text-xs text-slate-500">{request.id} · {request.type}</span><h2 className="mt-1 font-semibold">{request.title}</h2></div><div className="flex gap-2"><StatusPill tone={request.priority === "Bloquante" || request.priority === "Urgente" ? "danger" : "warning"}>{request.priority}</StatusPill><StatusPill tone={request.status === "Terminée" ? "success" : "info"}>{request.status}</StatusPill></div></div><p className="mt-2 text-sm text-slate-600">{request.description}</p><p className="mt-3 text-xs text-slate-500">{request.requester} → {request.responsible} · échéance {formatEuropeanDate(request.dueDate)}</p></Link>) : <EmptyState title="Aucune demande" description="Aucune demande ne correspond aux filtres." />}</div></div>;
}
