"use client";

import Link from "next/link";
import { useState } from "react";
import { EmptyState, fieldClass, formatEuropeanDate, ModuleHeader, primaryButton, secondaryButton, StatusPill } from "@/components/ui/ModuleUi";
import { updateDemoData, useDemoData } from "@/features/demo/services/demo-repository";
import { ActionFormDialog } from "@/features/actions/components/ActionFormDialog";
import type { RequestStatus } from "@/features/demo/types/demo";

const statuses: RequestStatus[] = ["Reçue", "En analyse", "Acceptée", "Planifiée", "En cours", "Terminée"];
export function RequestDetail({ id }: { id: string }) { const data = useDemoData(); const selectedRequest = data.requests.find((item) => item.id === id); const [comment, setComment] = useState(""); const [creatingAction, setCreatingAction] = useState(false); if (!selectedRequest) return <EmptyState title="Demande introuvable" description="Cette demande n’existe plus." />; const request = selectedRequest; const activeIndex = Math.max(0, statuses.indexOf(request.status)); function updateStatus(status: RequestStatus) { updateDemoData((draft) => { const target = draft.requests.find((item) => item.id === id); if (target) { target.status = status; target.history.unshift({ id: crypto.randomUUID(), date: new Date().toISOString(), author: "Daniel Mülverstedt", description: `Statut : ${status}` }); } }); } function addComment() { if (!comment.trim()) return; updateDemoData((draft) => { draft.requests.find((item) => item.id === id)?.comments.push(comment.trim()); }); setComment(""); }
  return <div className="mx-auto max-w-5xl"><ModuleHeader eyebrow={`${request.id} · ${request.type}`} title={request.title} description={request.description} actions={<Link href="/suivi" className={secondaryButton}>Retour</Link>} />
    {creatingAction ? <ActionFormDialog origine="Centre de demandes" contextLink={{ module: "request", id: request.id, label: request.id, href: `/suivi/${request.id}` }} onClose={() => setCreatingAction(false)} /> : null}
    <section className="mt-6 rounded-2xl border border-[var(--app-border)] bg-white p-5"><div className="flex flex-wrap gap-2">{statuses.map((status, index) => <button key={status} onClick={() => updateStatus(status)} className={`rounded-full px-3 py-2 text-xs font-semibold ${index <= activeIndex ? "bg-[var(--app-primary)] text-white" : "bg-slate-100 text-slate-500"}`}>{status}</button>)}</div><div className="mt-6 grid gap-4 text-sm sm:grid-cols-2"><Info label="Demandeur" value={request.requester} /><div><dt className="text-xs font-semibold uppercase text-slate-500">Responsable</dt><dd className="mt-1"><select className={fieldClass} value={request.responsible} onChange={(event) => updateDemoData((draft) => { const target = draft.requests.find((item) => item.id === id); if (target) target.responsible = event.target.value; })}>{[...new Set(data.actions.map((item) => item.responsable).concat(request.responsible))].map((item) => <option key={item}>{item}</option>)}</select></dd></div><Info label="Priorité" value={<StatusPill tone={request.priority === "Bloquante" || request.priority === "Urgente" ? "danger" : "warning"}>{request.priority}</StatusPill>} /><Info label="Échéance" value={formatEuropeanDate(request.dueDate)} /><Info label="OF lié" value={request.workOrderId ? <Link href={`/of/${request.workOrderId}`} className="underline">{request.workOrderId}</Link> : "Aucun"} /><Info label="Machine" value={request.machineId ?? "Aucune"} /></div><div className="mt-6 flex flex-wrap gap-2"><button className={primaryButton} onClick={() => setCreatingAction(true)}>Créer une action</button><input className={fieldClass} value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Ajouter un commentaire" /><button className={secondaryButton} onClick={addComment}>Commenter</button></div></section><section className="mt-5 rounded-2xl border border-[var(--app-border)] bg-white p-5"><h2 className="font-semibold">Historique</h2><ol className="mt-4 space-y-4 border-l pl-4">{request.history.map((entry) => <li key={entry.id}><p className="text-sm">{entry.description}</p><p className="text-xs text-slate-500">{formatEuropeanDate(entry.date, true)} · {entry.author}</p></li>)}</ol></section></div>; }
function Info({ label, value }: { label: string; value: React.ReactNode }) { return <div><dt className="text-xs font-semibold uppercase text-slate-500">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
