"use client";

import Link from "next/link";
import { useState } from "react";
import { EmptyState, formatEuropeanDate, ModuleHeader, primaryButton, secondaryButton, StatusPill } from "@/components/ui/ModuleUi";
import { useDemoData } from "@/features/demo/services/demo-repository";
import { ActionFormDialog } from "@/features/actions/components/ActionFormDialog";

export function WorkOrderDetail({ id }: { id: string }) {
  const data = useDemoData();
  const order = data.workOrders.find((item) => item.id === id);
  const [creatingAction, setCreatingAction] = useState(false);
  if (!order) return <EmptyState title="OF introuvable" description="Cet ordre de fabrication n’existe pas dans la démonstration." />;
  const currentIndex = order.operations.findIndex((item) => item.status === "En cours" || item.status === "Bloquée");
  const current = order.operations[currentIndex >= 0 ? currentIndex : 0];
  const next = order.operations[currentIndex + 1];
  const linkedActions = data.actions.filter((item) => item.contextLink?.module === "workOrder" && item.contextLink.id === id);
  return <div className="mx-auto max-w-7xl"><ModuleHeader eyebrow={order.id} title={order.description} description={`${order.customer} · ${order.article} · ${order.project}`} actions={<><button className={primaryButton} onClick={() => setCreatingAction(true)}>Créer une action</button><Link href="/of" className={secondaryButton}>Retour aux OF</Link></>} />
    {creatingAction ? <ActionFormDialog origine="Planning" contextLink={{ module: "workOrder", id: order.id, label: order.id, href: `/of/${order.id}` }} onClose={() => setCreatingAction(false)} /> : null}
    <section className="mt-6 grid gap-4 rounded-2xl border border-[var(--app-border)] bg-white p-5 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Quantité" value={`${order.quantity} pièces`} /><Metric label="Priorité" value={<StatusPill tone={order.priority === "Urgente" || order.priority === "Bloquante" ? "danger" : "warning"}>{order.priority}</StatusPill>} /><Metric label="Échéance client" value={formatEuropeanDate(order.dueDate)} /><Metric label="Statut" value={order.status} /><Metric label="Progression" value={`${order.progress} %`} /><Metric label="Opération actuelle" value={current ? `${current.number} · ${current.description}` : "Aucune"} /><Metric label="Opération suivante" value={next ? `${next.number} · ${next.description}` : "Fin de gamme"} /><Metric label="Machine actuelle" value={current?.machineId ?? "Non définie"} /></section>
    <section className="mt-5 rounded-2xl border border-[var(--app-border)] bg-white p-5"><h2 className="text-lg font-semibold">Gamme complète</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">N°</th><th className="p-3">Opération</th><th className="p-3">Département</th><th className="p-3">Machine</th><th className="p-3">Durée</th><th className="p-3">Date</th><th className="p-3">Statut</th><th className="p-3">Quantité</th><th className="p-3">Blocage</th></tr></thead><tbody>{order.operations.map((operation) => <tr key={operation.id} className="border-b last:border-0"><td className="p-3 font-semibold">{operation.number}</td><td className="p-3">{operation.description}</td><td className="p-3">{operation.department}</td><td className="p-3">{operation.machineId ?? "—"}</td><td className="p-3">{operation.plannedDurationHours} h</td><td className="p-3">{operation.plannedDate ? formatEuropeanDate(operation.plannedDate) : "—"}</td><td className="p-3"><StatusPill tone={operation.status === "Bloquée" ? "danger" : operation.status === "Terminée" ? "success" : "info"}>{operation.status}</StatusPill></td><td className="p-3">{operation.completedQuantity} / {order.quantity}</td><td className="p-3 text-red-700">{operation.blockingIssue ?? "—"}</td></tr>)}</tbody></table></div></section>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-[var(--app-border)] bg-white p-5"><h2 className="font-semibold">Actions liées</h2><ul className="mt-3 space-y-2">{linkedActions.length ? linkedActions.map((action) => <li key={action.id}><Link className="block rounded-lg bg-slate-50 p-3 text-sm hover:bg-slate-100" href={`/actions/${action.id}`}><strong>{action.id} · {action.description}</strong><span className="mt-1 block text-xs text-slate-500">{action.responsable} · {action.statut}</span></Link></li>) : <li className="text-sm text-slate-500">Aucune action liée.</li>}</ul></section><section className="rounded-2xl border border-[var(--app-border)] bg-white p-5"><h2 className="font-semibold">Problèmes de données</h2><ul className="mt-3 space-y-2 text-sm">{order.dataProblems.length ? order.dataProblems.map((problem) => <li className="rounded-lg bg-amber-50 p-3 text-amber-800" key={problem}>{problem}</li>) : <li className="text-slate-500">Aucun problème détecté.</li>}</ul><h3 className="mt-5 font-semibold">Historique</h3>{order.history.map((entry) => <p key={entry.id} className="mt-2 text-sm text-slate-600">{formatEuropeanDate(entry.date, true)} · {entry.description}</p>)}</section></div>
  </div>;
}

function Metric({ label, value }: { label: string; value: React.ReactNode }) { return <div><dt className="text-xs font-semibold uppercase text-slate-500">{label}</dt><dd className="mt-1 text-sm font-semibold">{value}</dd></div>; }
