import type { MailReasoningDependency, MailReasoningExecution, MailReasoningObject, MailReasoningReport, MailReasoningSnapshot, ReasoningRecord } from "@/features/mail-reasoning/types/mail-reasoning";

export function reasonFromSnapshot(snapshot: MailReasoningSnapshot, now = new Date()): MailReasoningReport {
  const objects: MailReasoningObject[] = [];
  const dependencies: MailReasoningDependency[] = [];
  for (const record of snapshot.records) {
    const overdue = isOverdue(record, now);
    if (record.type === "follow_up" && record.status !== "completed") add(objects, record, overdue ? "risk" : "waiting_item", overdue ? "Relance en retard" : "Suivi en attente", overdue ? "L’échéance de cette relance est dépassée." : "Cette relance attend encore une réponse ou une action.", overdue ? "high" : "medium", overdue ? "L’échéance connue est passée et le suivi reste ouvert." : "Un suivi ouvert reste sans résultat confirmé.", overdue ? "create_follow_up" : "wait", now, overdue ? 0.98 : 0.9);
    if (["reply", "draft"].includes(record.type) && ["pending", "prepared", "approved"].includes(record.status)) add(objects, record, "waiting_item", "Validation en attente", record.title, "medium", "Une réponse est prête mais ne doit pas progresser sans validation.", "ask_confirmation", now, 0.99);
    if (record.type === "commitment" && !["completed", "cancelled"].includes(record.status)) add(objects, record, overdue ? "risk" : "commitment", overdue ? "Engagement en retard" : "Engagement à suivre", record.title, overdue ? "high" : "medium", overdue ? "L’engagement confirmé a dépassé son échéance." : "Un engagement ouvert possède encore une suite attendue.", overdue ? "escalate" : "create_follow_up", now, 0.96);
    if (record.type === "meeting" && ["prepared", "awaiting_information"].includes(record.status)) add(objects, record, "recommendation", "Réunion à confirmer", record.title, "low", "Une proposition existe mais aucune création externe n’est autorisée sans confirmation.", "schedule_meeting", now, 0.95);
    if (record.type === "session" && record.status === "ready") add(objects, record, "blocked_item", "Session à reprendre", record.title, "medium", "Des sujets non résolus restent attachés à une session précédente.", "review", now, 0.97);
    if (record.type === "decision" && record.status === "proposed") add(objects, record, "decision_impact", "Décision à confirmer", record.title, "medium", "Cette décision peut modifier la suite du dossier mais n’est pas confirmée.", "ask_confirmation", now, 0.94);
    if (record.type === "action" && record.status !== "completed") add(objects, record, overdue ? "deadline" : "dependency", overdue ? "Échéance dépassée" : "Action dépendante", record.title, overdue ? "high" : "medium", overdue ? "Une action locale ouverte a dépassé son échéance." : "Cette action doit être suivie avant de clore le dossier.", overdue ? "escalate" : "review", now, 0.93);
    if (record.type === "message" && record.status === "reply_required" && now.getTime() - new Date(record.updatedAt).getTime() > 3 * 86_400_000) add(objects, record, "risk", "Réponse attendue depuis plusieurs jours", record.title, "high", "Le message nécessite une réponse depuis plus de trois jours.", "reply_now", now, 0.91);
  }
  detectConflicts(snapshot.records, objects, now);
  detectOpportunities(snapshot.records, objects, dependencies, now);
  connectSharedSources(objects, dependencies);
  objects.sort((a, b) => rank(b.severity) - rank(a.severity) || b.confidence - a.confidence);
  return { objects, dependencies, execution: { mode: "local", reason: "Règles déterministes sur la mémoire locale", tokenEstimate: 0, aiCalled: false }, generatedAt: now.toISOString() };
}

export function selectReasoningExecution(input: { deterministicSufficient: boolean; cacheAvailable: boolean; explicitAiConsent: boolean; estimatedTokens?: number }): MailReasoningExecution {
  if (input.deterministicSufficient) return { mode: "local", reason: "Les faits structurés suffisent", tokenEstimate: 0, aiCalled: false };
  if (input.cacheAvailable) return { mode: "cached", reason: "Une synthèse compatible existe en cache", tokenEstimate: 0, aiCalled: false };
  if (input.explicitAiConsent) return { mode: "ai", reason: "Synthèse complexe explicitement demandée", tokenEstimate: input.estimatedTokens ?? 0, aiCalled: true };
  return { mode: "local", reason: "Synthèse complexe bloquée en attente de consentement", tokenEstimate: 0, aiCalled: false };
}

function add(objects: MailReasoningObject[], record: ReasoningRecord, kind: MailReasoningObject["kind"], title: string, description: string, severity: MailReasoningObject["severity"], reason: string, action: MailReasoningObject["recommendedAction"], now: Date, confidence: number) { objects.push(makeObject(record, kind, title, description, severity, reason, action, now, confidence)); }
function makeObject(record: ReasoningRecord, kind: MailReasoningObject["kind"], title: string, description: string, severity: MailReasoningObject["severity"], reason: string, action: MailReasoningObject["recommendedAction"], now: Date, confidence: number): MailReasoningObject { return { id: `reason:${kind}:${record.id}`, kind, title, description, confidence, severity, reason, supportingSources: [source(record)], createdAt: now.toISOString(), updatedAt: now.toISOString(), status: kind === "waiting_item" ? "waiting" : kind === "recommendation" ? "recommended" : "open", recommendedAction: action }; }
function source(record: ReasoningRecord) { return { recordId: record.id, sourceId: record.sourceId, sourceType: record.type, sourceLinkIds: record.sourceLinkIds, fact: record.title }; }
function isOverdue(record: ReasoningRecord, now: Date) { return Boolean(record.dueAt && new Date(record.dueAt).getTime() < now.getTime()); }
function detectConflicts(records: ReasoningRecord[], objects: MailReasoningObject[], now: Date) { const list = records.filter((item) => item.type === "commitment" && item.dueAt && !["completed", "cancelled"].includes(item.status)); for (let i = 0; i < list.length; i += 1) for (let j = i + 1; j < list.length; j += 1) if (list[i].dueAt === list[j].dueAt && list[i].stakeholder === list[j].stakeholder) { const item = makeObject(list[i], "conflict", "Engagements potentiellement contradictoires", `${list[i].title} et ${list[j].title} partagent la même échéance et le même interlocuteur.`, "high", "Deux engagements ouverts se superposent ; leur compatibilité doit être confirmée.", "ask_confirmation", now, 0.82); item.supportingSources = [source(list[i]), source(list[j])]; objects.push(item); } }
function detectOpportunities(records: ReasoningRecord[], objects: MailReasoningObject[], dependencies: MailReasoningDependency[], now: Date) { const groups = new Map<string, ReasoningRecord[]>(); for (const item of records.filter((entry) => entry.type === "reply" && entry.status === "pending")) { const key = item.threadId ?? item.sourceId; groups.set(key, [...(groups.get(key) ?? []), item]); } for (const group of groups.values()) if (group.length > 1) { const item = makeObject(group[0], "opportunity", "Réponses regroupables", `${group.length} réponses concernent la même conversation.`, "low", "Un traitement groupé évite un travail en double.", "review", now, 0.9); item.supportingSources = group.map(source); objects.push(item); for (const other of group.slice(1)) dependencies.push({ fromId: group[0].id, toId: other.id, relation: "duplicates", reason: "Même conversation" }); } }
function connectSharedSources(objects: MailReasoningObject[], dependencies: MailReasoningDependency[]) { for (let i = 0; i < objects.length; i += 1) for (let j = i + 1; j < objects.length; j += 1) if (objects[i].supportingSources.some((a) => a.sourceLinkIds.some((id) => objects[j].supportingSources.some((b) => b.sourceLinkIds.includes(id))))) dependencies.push({ fromId: objects[i].id, toId: objects[j].id, relation: "impacts", reason: "Source métier partagée" }); }
function rank(value: MailReasoningObject["severity"]) { return ({ info: 0, low: 1, medium: 2, high: 3, critical: 4 })[value]; }
