"use client";
import type { TtsProvider, TtsRequest, TtsVoice } from "@/features/mail-assistant/services/tts-provider";

function synth(): SpeechSynthesis | null { return typeof window !== "undefined" && "speechSynthesis" in window ? window.speechSynthesis : null; }
export const browserTtsProvider: TtsProvider = {
  id: "system-browser", label: "Voix système gratuite", configured: true,
  supported: () => Boolean(synth() && typeof SpeechSynthesisUtterance !== "undefined"),
  voices: () => deduplicateVoices(synth()?.getVoices() ?? []),
  subscribeVoices(listener) { const engine = synth(); if (!engine) return () => undefined; engine.addEventListener("voiceschanged", listener); return () => engine.removeEventListener("voiceschanged", listener); },
  speak(request: TtsRequest) { const engine = synth(); if (!engine || typeof SpeechSynthesisUtterance === "undefined") { request.onError(); return; } engine.cancel(); const utterance = new SpeechSynthesisUtterance(request.text); utterance.lang = request.language; utterance.rate = request.rate; utterance.pitch = request.pitch; utterance.volume = request.volume; const available = engine.getVoices(); utterance.voice = available.find((voice) => voice.voiceURI === request.voiceId) ?? available.find((voice) => voice.name === request.voiceName && voice.lang === request.language) ?? available.find((voice) => voice.lang === request.language && voice.default) ?? available.find((voice) => voice.lang === request.language) ?? available.find((voice) => voice.default) ?? null; utterance.onstart = request.onStart; utterance.onend = request.onEnd; utterance.onerror = request.onError; engine.speak(utterance); },
  pause: () => synth()?.pause(), resume: () => synth()?.resume(), stop: () => synth()?.cancel(),
};
export const futureTtsProviders = [{ id: "openai-tts-future", label: "Voix premium via API — non configurée", configured: false }, { id: "other-future-provider", label: "Autre fournisseur premium — non configuré", configured: false }] as const;
export function deduplicateVoices(voices: SpeechSynthesisVoice[]): TtsVoice[] { const unique = new Map<string, TtsVoice>(); for (const voice of voices) { const id = voice.voiceURI || `${voice.name}:${voice.lang}`; unique.set(id, { id, uri: voice.voiceURI, name: voice.name, language: voice.lang.split("-")[0]?.toLowerCase() ?? voice.lang, locale: voice.lang, local: voice.localService, isDefault: voice.default, category: voice.lang.toLowerCase().startsWith("fr") ? "françaises" : voice.lang.toLowerCase().startsWith("en") ? "anglaises" : "autres" }); } return [...unique.values()].sort((a, b) => a.locale.localeCompare(b.locale) || a.name.localeCompare(b.name)); }
export function resolveVoiceFallback(voices: TtsVoice[], selected: { id: string; name: string; locale: string }): TtsVoice | null { return voices.find((voice) => voice.id === selected.id) ?? voices.find((voice) => voice.name === selected.name && voice.locale === selected.locale) ?? voices.find((voice) => voice.locale === selected.locale && voice.isDefault) ?? voices.find((voice) => voice.locale === selected.locale) ?? voices.find((voice) => voice.isDefault) ?? voices[0] ?? null; }
export function loadSystemVoices(onUpdate: (voices: TtsVoice[]) => void): () => void { let timer = 0; const refresh = () => { const voices = browserTtsProvider.voices(); onUpdate(voices); if (!voices.length) timer = window.setTimeout(refresh, 250); }; const unsubscribe = browserTtsProvider.subscribeVoices(refresh); refresh(); return () => { window.clearTimeout(timer); unsubscribe(); }; }
