"use client";

import Link from "next/link";
import { useState } from "react";
import { EmptyState, fieldClass, formatEuropeanDate, ModuleHeader, primaryButton, secondaryButton, StatusPill } from "@/components/ui/ModuleUi";
import { updateDemoData, useDemoData } from "@/features/demo/services/demo-repository";

export function ErpQualityDetail({ id }: { id: string }) { const data = useDemoData(); const selectedIssue = data.erpQuality.find((item) => item.id === id); const [emailVisible, setEmailVisible] = useState(false); const [notice, setNotice] = useState(""); if (!selectedIssue) return <EmptyState title="Anomalie introuvable" description="Cette anomalie n’existe plus." />; const issue = selectedIssue; const order = data.workOrders.find((item) => item.id === issue.workOrderId); const email = `Objet : Correction requise pour ${issue.workOrderId}\n\nBonjour ${issue.responsible},\n\nLe contrôle de qualité ERP a détecté : ${issue.problemType}.\n${issue.details}\n\nMerci de vérifier les données sources. Aucune modification automatique ne sera effectuée.\n\nBien cordialement,\nProdPilot IA`; function setStatus(status: "Envoyée" | "Résolue") { updateDemoData((draft) => { const target = draft.erpQuality.find((item) => item.id === id); if (target) target.status = status; }); setNotice(status === "Envoyée" ? "E-mail marqué comme envoyé dans la démonstration. Aucun message réel n’a été transmis." : "Anomalie marquée comme résolue localement."); } function createAction() { updateDemoData((draft) => { const actionId = `ACT-${String(draft.actions.length + 1).padStart(3, "0")}`; draft.actions.unshift({ id: actionId, title: `Corriger ${issue.problemType.toLowerCase()} · ${issue.workOrderId}`, description: issue.details, responsible: issue.responsible, department: "Qualité", priority: issue.severity === "Bloquante" ? "Bloquante" : issue.severity === "Élevée" ? "Haute" : "Normale", status: "Ouverte", dueDate: "2026-07-15", createdAt: "2026-07-13", sourceType: "erp_quality", sourceId: issue.id, workOrderId: issue.workOrderId, machineId: null, project: order?.project ?? null, comments: [], history: [{ id: crypto.randomUUID(), date: new Date().toISOString(), author: "Daniel Mülverstedt", description: `Action créée depuis ${issue.id}` }] }); }); setNotice("Action créée dans le module Actions."); }
  return <div className="mx-auto max-w-5xl"><ModuleHeader eyebrow={`${issue.id} · ${issue.problemType}`} title={issue.workOrderId} description={issue.details} actions={<Link href="/qualite-erp" className={secondaryButton}>Retour</Link>} /><section className="mt-6 rounded-2xl border border-[var(--app-border)] bg-white p-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="Client" value={order?.customer ?? "Manquant"} /><Info label="Article" value={order?.article ?? "Manquant"} /><Info label="Responsable" value={issue.responsible} /><Info label="Détection" value={formatEuropeanDate(issue.detectedAt)} /><Info label="Sévérité" value={<StatusPill tone={issue.severity === "Élevée" || issue.severity === "Bloquante" ? "danger" : "warning"}>{issue.severity}</StatusPill>} /><Info label="Score" value={`${issue.score}/100`} /><Info label="Statut" value={issue.status} /></div><div className="mt-6 flex flex-wrap gap-2"><button className={primaryButton} onClick={() => setEmailVisible(true)}>Générer l’e-mail mock</button><button className={secondaryButton} onClick={createAction}>Créer une action</button><button className={secondaryButton} onClick={() => setStatus("Résolue")}>Marquer résolue</button></div>{notice ? <p className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p> : null}{emailVisible ? <div className="mt-5 rounded-xl border bg-slate-50 p-4"><h2 className="font-semibold">E-mail de démonstration</h2><textarea className={`${fieldClass} mt-3 min-h-64 w-full whitespace-pre-wrap py-3`} value={email} readOnly /><div className="mt-3 flex gap-2"><button className={secondaryButton} onClick={() => { void navigator.clipboard.writeText(email); setNotice("E-mail copié dans le presse-papiers."); }}>Copier</button><button className={secondaryButton} onClick={() => setStatus("Envoyée")}>Marquer comme envoyé</button></div><p className="mt-2 text-xs text-slate-500">Aucun e-mail réel ne sera envoyé.</p></div> : null}</section></div>; }
function Info({ label, value }: { label: string; value: React.ReactNode }) { return <div><dt className="text-xs font-semibold uppercase text-slate-500">{label}</dt><dd className="mt-1 text-sm font-medium">{value}</dd></div>; }
