"use client";

import Link from "next/link";
import { useState } from "react";
import { EmptyState, fieldClass, formatEuropeanDate, ModuleHeader, primaryButton, secondaryButton, StatusPill } from "@/components/ui/ModuleUi";
import { updateDemoData, useDemoData } from "@/features/demo/services/demo-repository";
import { ActionFormDialog } from "@/features/actions/components/ActionFormDialog";

export function ErpQualityDetail({ id }: { id: string }) { const data = useDemoData(); const selectedIssue = data.erpQuality.find((item) => item.id === id); const [emailVisible, setEmailVisible] = useState(false); const [notice, setNotice] = useState(""); const [creatingAction, setCreatingAction] = useState(false); if (!selectedIssue) return <EmptyState title="Anomalie introuvable" description="Cette anomalie n’existe plus." />; const issue = selectedIssue; const order = data.workOrders.find((item) => item.id === issue.workOrderId); const linkedActions = data.actions.filter((item) => item.contextLinks.some((link) => link.module === "erpQuality" && link.id === issue.id)); const email = `Objet : Correction requise pour ${issue.workOrderId}\n\nBonjour ${issue.responsible},\n\nLe contrôle de qualité ERP a détecté : ${issue.problemType}.\n${issue.details}\n\nMerci de vérifier les données sources. Aucune modification automatique ne sera effectuée.\n\nBien cordialement,\nProdPilot IA`; function setStatus(status: "Envoyée" | "Résolue") { updateDemoData((draft) => { const target = draft.erpQuality.find((item) => item.id === id); if (target) target.status = status; }); setNotice(status === "Envoyée" ? "E-mail marqué comme envoyé dans la démonstration. Aucun message réel n’a été transmis." : "Anomalie marquée comme résolue localement."); }
  return <div className="mx-auto max-w-5xl"><ModuleHeader eyebrow={`${issue.id} · ${issue.problemType}`} title={issue.workOrderId} description={issue.details} actions={<Link href="/qualite-erp" className={secondaryButton}>Retour</Link>} />
    {creatingAction ? <ActionFormDialog origine="Qualité ERP" contextLink={{ module: "erpQuality", id: issue.id, label: issue.id, href: `/qualite-erp/${issue.id}` }} onClose={() => setCreatingAction(false)} onCreated={() => setNotice("Action créée dans le registre Actions.")} /> : null}
    <section className="mt-6 rounded-2xl border border-[var(--app-border)] bg-white p-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="Client" value={order?.customer ?? "Manquant"} /><Info label="Article" value={order?.article ?? "Manquant"} /><Info label="Responsable" value={issue.responsible} /><Info label="Détection" value={formatEuropeanDate(issue.detectedAt)} /><Info label="Sévérité" value={<StatusPill tone={issue.severity === "Élevée" || issue.severity === "Bloquante" ? "danger" : "warning"}>{issue.severity}</StatusPill>} /><Info label="Score" value={`${issue.score}/100`} /><Info label="Statut" value={issue.status} /></div><div className="mt-6 flex flex-wrap gap-2"><button className={primaryButton} onClick={() => setEmailVisible(true)}>Générer l’e-mail mock</button><button className={secondaryButton} onClick={() => setCreatingAction(true)}>Créer une action</button><button className={secondaryButton} onClick={() => setStatus("Résolue")}>Marquer résolue</button></div>{notice ? <p className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p> : null}{emailVisible ? <div className="mt-5 rounded-xl border bg-slate-50 p-4"><h2 className="font-semibold">E-mail de démonstration</h2><textarea className={`${fieldClass} mt-3 min-h-64 w-full whitespace-pre-wrap py-3`} value={email} readOnly /><div className="mt-3 flex gap-2"><button className={secondaryButton} onClick={() => { void navigator.clipboard.writeText(email); setNotice("E-mail copié dans le presse-papiers."); }}>Copier</button><button className={secondaryButton} onClick={() => setStatus("Envoyée")}>Marquer comme envoyé</button></div><p className="mt-2 text-xs text-slate-500">Aucun e-mail réel ne sera envoyé.</p></div> : null}</section>
    <section className="mt-5 rounded-2xl border border-[var(--app-border)] bg-white p-5"><h2 className="font-semibold">Actions liées</h2><ul className="mt-3 space-y-2">{linkedActions.length ? linkedActions.map((action) => <li key={action.id}><Link className="block rounded-lg bg-slate-50 p-3 text-sm hover:bg-slate-100" href={`/actions/${action.id}`}><strong>{action.id} · {action.description}</strong><span className="mt-1 block text-xs text-slate-500">{action.responsable} · {action.statut}</span></Link></li>) : <li className="text-sm text-slate-500">Aucune action liée.</li>}</ul></section></div>; }
function Info({ label, value }: { label: string; value: React.ReactNode }) { return <div><dt className="text-xs font-semibold uppercase text-slate-500">{label}</dt><dd className="mt-1 text-sm font-medium">{value}</dd></div>; }
