"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { fieldClass, formatEuropeanDate, primaryButton, secondaryButton, StatusPill } from "@/components/ui/ModuleUi";
import { ContactPickerDialog } from "@/features/contacts/components/ContactPickerDialog";
import { contactFullName } from "@/features/contacts/services/contact-directory";
import { useDemoData } from "@/features/demo/services/demo-repository";
import { MailDraftSendPanel } from "@/features/meetings/components/MailDraftSendPanel";
import { MeetingRecap } from "@/features/meetings/components/MeetingRecap";
import { initializeMeetingRecapDocument, recordMeetingRecapSent, updateMeetingRecapDocument } from "@/features/meetings/services/meeting-recap-document-service";
import { buildMeetingRecapEmail, buildMeetingRecapEmailHtml, buildMeetingRecapInlineImages } from "@/features/meetings/services/meeting-recap-email";
import { buildMeetingPreparationDocument } from "@/features/meetings/services/meeting-preparation-document";
import { buildMeetingRecapPdf } from "@/features/meetings/services/meeting-recap-pdf";
import { PlanningDialogShell } from "@/features/planning/components/PlanningDialogShell";
import { useSettings } from "@/features/settings/components/SettingsProvider";
import type { GeneratedMailAttachment } from "@/features/meetings/services/meeting-planning-pdf";
import type { Meeting, ProductionAction } from "@/features/demo/types/demo";

export function MeetingRecapWorkspace({ meeting, actions, onArchive }: { meeting: Meeting; actions: ProductionAction[]; onArchive: () => void }) {
  const data = useDemoData(); const { settings } = useSettings();
  const [editing, setEditing] = useState(false); const [sending, setSending] = useState(false); const [picking, setPicking] = useState(false); const [attachments, setAttachments] = useState<GeneratedMailAttachment[]>([]);
  const machineNames = useMemo(() => Object.fromEntries(settings.production.machines.map((item) => [item.id, item.displayName])), [settings.production.machines]);
  const generated = useMemo(() => buildMeetingRecapEmail(meeting, meeting.type, actions, data.contacts, data.maintenanceProblems, machineNames), [actions, data.contacts, data.maintenanceProblems, machineNames, meeting]);
  const initialRecipients = useMemo(() => meeting.participants.filter((item) => item.present).map((item) => item.contactId), [meeting.participants]);
  const document = meeting.recapDocument;
  const recapBranding = useMemo(() => ({ companyName: settings.company.name, footerText: settings.company.footerText, logoDataUrl: settings.company.logoDataUrl }), [settings.company.footerText, settings.company.logoDataUrl, settings.company.name]);
  const recapEmailHtml = useMemo(() => document ? buildMeetingRecapEmailHtml({ subject: document.subject, mailBody: document.mailBody, documentBody: document.documentBody, ...recapBranding }) : undefined, [document, recapBranding]);
  const recapInlineImages = useMemo(() => buildMeetingRecapInlineImages(recapBranding.logoDataUrl), [recapBranding.logoDataUrl]);
  useEffect(() => { if (!document) initializeMeetingRecapDocument(meeting.id, { subject: generated.subject, mailBody: "Bonjour,\n\nVeuillez trouver ci-joint le compte rendu de la réunion de production.\n\nVous trouverez également les actions créées ainsi que les principaux sujets abordés.\n\nBonne journée.", documentBody: generated.bodyText, recipientContactIds: initialRecipients }); }, [document, generated.bodyText, generated.subject, initialRecipients, meeting.id]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (!sending || !document) { setAttachments([]); return; } let active = true; const workOrders = data.workOrders.filter((order) => meeting.priorityDossiers.some((item) => item.referenceId === order.id)); const preparation = buildMeetingPreparationDocument(meeting, meeting.type, actions.filter((item) => item.statut !== "Fait"), workOrders, data.contacts, data.maintenanceProblems, machineNames); const actionText = actions.map((item) => `${item.description} — ${item.responsable || "sans responsable"} — ${item.echeance} — ${item.statut}`).join("\n"); const jobs: Promise<GeneratedMailAttachment>[] = []; if (document.includePdf) jobs.push(buildMeetingRecapPdf(document.subject, document.documentBody, recapBranding)); if (document.includeActions) jobs.push(buildMeetingRecapPdf("Liste des actions", actionText, recapBranding).then((item) => ({ ...item, filename: "liste-actions.pdf" }))); if (document.includePreparation) jobs.push(buildMeetingRecapPdf(preparation.subject, preparation.bodyText, recapBranding).then((item) => ({ ...item, filename: "preparation-reunion.pdf" }))); void Promise.all(jobs).then((items) => { if (active) setAttachments(items); }); return () => { active = false; }; }, [actions, data.contacts, data.maintenanceProblems, data.workOrders, document, machineNames, meeting, recapBranding, sending]);
  if (!document) return <p className="rounded-xl bg-slate-50 p-4 text-sm">Génération du compte rendu…</p>;
  const recipients = document.recipientContactIds.map((id) => data.contacts.find((item) => item.id === id)).filter((item) => item !== undefined);
  const resolved = recipients.filter((item) => item.email).map((item) => ({ name: contactFullName(item), email: item.email! })); const unresolved = recipients.filter((item) => !item.email).map(contactFullName);
  const duration = meeting.startedAt && meeting.closedAt ? Math.max(0, Math.round((new Date(meeting.closedAt).getTime() - new Date(meeting.startedAt).getTime()) / 60000)) : null;
  const handled = meeting.priorityDossiers.filter((item) => item.status === "Décision prise").length; const postponed = meeting.priorityDossiers.filter((item) => item.status === "Reporté").length;
  const attachmentNames = [document.includePdf ? "compte-rendu-reunion.pdf" : null, document.includeActions ? "liste-actions" : null, document.includePreparation ? "preparation-reunion" : null].filter((item): item is string => Boolean(item));
  function downloadPdf() { const { subject, documentBody } = document!; void buildMeetingRecapPdf(subject, documentBody, recapBranding).then((attachment) => { const bytes = Uint8Array.from(atob(attachment.base64), (character) => character.charCodeAt(0)); const url = URL.createObjectURL(new Blob([bytes], { type: attachment.mimeType })); const link = window.document.createElement("a"); link.href = url; link.download = attachment.filename; link.click(); URL.revokeObjectURL(url); }); }
  return <div className="mt-6">
    <div className="sticky top-0 z-10 rounded-2xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-semibold uppercase text-[var(--app-primary)]">Compte rendu</p><h2 className="text-xl font-bold">{meeting.type === "Production" ? "Réunion Production" : "QRQC quotidien"}</h2><p className="text-sm text-slate-500">{formatEuropeanDate(meeting.date, true)} · {duration === null ? "Durée non mesurée" : `${duration} min`} · Statut : {document.status}</p></div><div className="flex flex-wrap gap-2"><button className={secondaryButton} onClick={() => setEditing((value) => !value)}>{editing ? "Terminer" : "Modifier"}</button><button className={secondaryButton} onClick={() => updateMeetingRecapDocument(meeting.id, { documentBody: generated.bodyText, subject: generated.subject, status: "À relire" })}>Générer</button><button className={secondaryButton} onClick={downloadPdf}>Exporter PDF</button><button className={primaryButton} onClick={() => setSending(true)}>Envoyer</button></div></div></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-3"><Summary label="Préparation" value={`${meeting.priorityDossiers.length} dossier(s)`} /><Summary label="Compte rendu" value={`✓ ${handled} traité(s)${postponed ? ` · ⚠ ${postponed} reporté(s)` : ""}`} /><Summary label="Actions liées" value={String(actions.length)} /></div>
    <section className="mt-4 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between"><h3 className="font-semibold">Aperçu du document</h3><StatusPill tone={document.status === "Envoyé" ? "success" : document.status === "Prêt" ? "info" : "warning"}>{document.status}</StatusPill></div>{editing ? <textarea className={`${fieldClass} mt-4 min-h-[620px] w-full font-mono text-sm leading-6`} value={document.documentBody} onChange={(event) => updateMeetingRecapDocument(meeting.id, { documentBody: event.target.value, status: "À relire" })} /> : <pre className="mt-5 whitespace-pre-wrap font-sans text-sm leading-6">{document.documentBody}</pre>}</section>
    <section className="mt-5 rounded-2xl border bg-white p-5"><h3 className="font-semibold">Vue synthétique</h3><div className="mt-4"><MeetingRecap meeting={meeting} actions={actions} /></div></section>
    {document.sentVersions.length ? <details className="mt-4 rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold">Historique des envois — {document.sentVersions.length}</summary>{[...document.sentVersions].reverse().map((version) => <div key={version.id} className="mt-3 border-t pt-3 text-sm"><strong>{formatEuropeanDate(version.sentAt, true)}</strong><p>{version.recipientEmails.join(", ")} · {version.subject}</p></div>)}</details> : null}
    <div className="mt-5 flex justify-between"><Link href="/reunions" className={secondaryButton}>Retour à la réunion</Link><button className={primaryButton} onClick={onArchive}>Archiver</button></div>
    {sending ? <PlanningDialogShell title="Envoyer le compte rendu" description="Relisez les destinataires, l’objet, le message et les pièces jointes." maxWidthClassName="max-w-3xl" onClose={() => setSending(false)} actions={<button className={secondaryButton} onClick={() => setSending(false)}>Fermer</button>}><div className="grid gap-3"><div className="flex justify-between"><strong className="text-sm">Destinataires</strong><button className={secondaryButton} onClick={() => setPicking(true)}>Ajouter un destinataire</button></div><div className="flex flex-wrap gap-2">{recipients.map((contact) => <label key={contact.id} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs"><input type="checkbox" checked onChange={() => updateMeetingRecapDocument(meeting.id, { recipientContactIds: document.recipientContactIds.filter((id) => id !== contact.id) })} /> {contactFullName(contact)}</label>)}</div><label className="text-sm font-semibold">Objet<input className={`${fieldClass} mt-1 w-full`} value={document.subject} onChange={(event) => updateMeetingRecapDocument(meeting.id, { subject: event.target.value })} /></label><label className="text-sm font-semibold">Corps du mail<textarea className={`${fieldClass} mt-1 min-h-32 w-full`} value={document.mailBody} onChange={(event) => updateMeetingRecapDocument(meeting.id, { mailBody: event.target.value })} /></label><label><input type="checkbox" checked={document.includePdf} onChange={(event) => updateMeetingRecapDocument(meeting.id, { includePdf: event.target.checked })} /> Compte rendu PDF</label><label><input type="checkbox" checked={document.includeActions} onChange={(event) => updateMeetingRecapDocument(meeting.id, { includeActions: event.target.checked })} /> Liste des actions</label><label><input type="checkbox" checked={document.includePreparation} onChange={(event) => updateMeetingRecapDocument(meeting.id, { includePreparation: event.target.checked })} /> Préparation de la réunion</label><MailDraftSendPanel label="Préparer l’e-mail" resolved={resolved} unresolved={unresolved} subject={document.subject} bodyText={document.mailBody} bodyHtml={recapEmailHtml} inlineImages={recapInlineImages} attachments={attachments} draftKey={`meeting-recap-${meeting.id}-${document.updatedAt}`} onSent={() => recordMeetingRecapSent(meeting.id, resolved.map((item) => item.email), attachmentNames)} className="mt-2 border-t pt-4" /></div></PlanningDialogShell> : null}
    {picking ? <ContactPickerDialog title="Ajouter des destinataires" excludeIds={document.recipientContactIds} onConfirm={(ids) => updateMeetingRecapDocument(meeting.id, { recipientContactIds: [...new Set([...document.recipientContactIds, ...ids])] })} onClose={() => setPicking(false)} /> : null}
  </div>;
}
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border bg-white p-3"><span className="text-xs text-slate-500">{label}</span><strong className="block">{value}</strong></div>; }
