import type { MailReasoningReport } from "@/features/mail-reasoning/types/mail-reasoning";

const ACTIONS = { reply_now: "Répondre maintenant", wait: "Attendre", create_follow_up: "Préparer une relance", schedule_meeting: "Préparer une réunion", call_supplier: "Appeler le fournisseur", ask_confirmation: "Demander confirmation", escalate: "Signaler", archive: "Archiver", review: "Examiner" } as const;

export function MailReasoningRecommendations({ report }: { report: MailReasoningReport | null }) {
  const recommendations = report?.objects.slice(0, 4) ?? [];
  return <section className="mt-20" aria-labelledby="assistant-recommendations-title"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[#d8f567]/70">Assistant Recommendations</p><h2 id="assistant-recommendations-title" className="mt-2 text-3xl font-medium tracking-[-0.035em]">Ce qui mérite votre attention</h2></div>{report ? <p className="text-xs text-white/35">{report.execution.mode === "local" ? "Raisonnement local" : "Raisonnement assisté"} · {report.execution.tokenEstimate} jeton estimé</p> : null}</div><div className="mt-6 grid gap-4 md:grid-cols-2">{recommendations.length ? recommendations.map((item) => <article key={item.id} className="rounded-[1.5rem] border border-white/[0.07] bg-white/[0.055] p-5"><div className="flex items-center justify-between gap-4"><span className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-300/75">{label(item.kind)}</span><span className="text-xs text-white/35">Confiance {Math.round(item.confidence * 100)} %</span></div><h3 className="mt-4 text-xl font-medium">{item.title}</h3><p className="mt-2 text-sm leading-6 text-white/55">{item.description}</p><details className="mt-4 text-sm"><summary className="cursor-pointer text-white/45">Pourquoi cette recommandation ?</summary><p className="mt-2 leading-6 text-white/55">{item.reason}</p><p className="mt-2 text-xs text-white/30">{item.supportingSources.length} source{item.supportingSources.length > 1 ? "s" : ""} locale{item.supportingSources.length > 1 ? "s" : ""}</p></details>{item.recommendedAction ? <p className="mt-5 text-sm font-semibold text-[#d8f567]">Action suggérée : {ACTIONS[item.recommendedAction]}</p> : null}</article>) : <p className="rounded-[1.5rem] bg-white/[0.04] p-5 text-sm text-white/45 md:col-span-2">Aucun risque, blocage ou suivi prioritaire détecté dans la mémoire locale.</p>}</div></section>;
}
function label(kind: string) { return ({ risk: "Risque", opportunity: "Opportunité", recommendation: "Recommandation", dependency: "Dépendance", blocked_item: "Blocage", waiting_item: "En attente", conflict: "Conflit", deadline: "Échéance", commitment: "Engagement", decision_impact: "Impact décision" } as Record<string, string>)[kind] ?? kind; }
