"use client";

import { useState } from "react";
import { useSettings } from "@/features/settings/components/SettingsProvider";
import { buttonClass, inputClass, SettingsPanel } from "@/features/settings/components/SettingsUi";
import type { ModulePermission } from "@/features/settings/types/settings";

const permissionLabels: Record<keyof ModulePermission, string> = { visible: "Visible", view: "Voir", create: "Créer", edit: "Modifier", delete: "Supprimer", print: "Imprimer", export: "Exporter", administer: "Administrer" };

export function UsersPermissionsSettings() {
  const { settings, updateSettings } = useSettings();
  const [roleId, setRoleId] = useState(settings.roles[0]?.id ?? "");
  const role = settings.roles.find((item) => item.id === roleId) ?? settings.roles[0];
  return <div className="space-y-5"><SettingsPanel title="Utilisateurs" description="Comptes de démonstration conservés localement."><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b border-[var(--app-border)] text-xs uppercase text-slate-500"><th className="p-3">Actif</th><th className="p-3">Nom</th><th className="p-3">E-mail</th><th className="p-3">Rôle</th></tr></thead><tbody>{settings.users.map((user) => <tr className="border-b border-slate-100" key={user.id}><td className="p-3"><input type="checkbox" checked={user.active} onChange={(event) => updateSettings((draft) => { const target = draft.users.find((item) => item.id === user.id); if (target) target.active = event.target.checked; }, "Utilisateur modifié")} /></td><td className="p-3 font-medium">{user.firstName} {user.lastName}</td><td className="p-3">{user.email}</td><td className="p-3"><select className={inputClass} value={user.roleId} onChange={(event) => updateSettings((draft) => { const target = draft.users.find((item) => item.id === user.id); if (target) target.roleId = event.target.value; }, "Rôle utilisateur modifié")}>{settings.roles.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></td></tr>)}</tbody></table></div></SettingsPanel>
  <SettingsPanel title="Rôles et droits" description="Le droit Visible pilote immédiatement le menu latéral."><label className="mb-4 block max-w-sm text-sm font-medium">Rôle<select className={`${inputClass} mt-1`} value={role?.id} onChange={(event) => setRoleId(event.target.value)}>{settings.roles.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-center text-xs"><thead><tr className="border-b border-[var(--app-border)]"><th className="p-3 text-left">Module</th>{Object.values(permissionLabels).map((label) => <th className="p-3" key={label}>{label}</th>)}</tr></thead><tbody>{settings.navigation.map((module) => <tr className="border-b border-slate-100" key={module.id}><th className="p-3 text-left font-medium">{module.label}</th>{(Object.keys(permissionLabels) as (keyof ModulePermission)[]).map((permission) => <td className="p-3" key={permission}><input type="checkbox" aria-label={`${permissionLabels[permission]} ${module.label}`} checked={role?.permissions[module.id]?.[permission] ?? false} onChange={(event) => updateSettings((draft) => { const target = draft.roles.find((item) => item.id === role?.id); if (target?.permissions[module.id]) target.permissions[module.id][permission] = event.target.checked; }, "Droits du rôle modifiés")} /></td>)}</tr>)}</tbody></table></div></SettingsPanel></div>;
}

export function PrintSettingsPanel() {
  const { settings, updateSettings } = useSettings();
  const columns = [...settings.print.columns].sort((a, b) => a.order - b.order);
  return <SettingsPanel title="Impression" description="Préparez les colonnes et le format des futures fiches d’OF."><div className="mb-5 flex flex-wrap gap-4"><label className="text-sm font-medium">Papier<select className={`${inputClass} mt-1 w-28`} value={settings.print.paperSize} onChange={(event) => updateSettings((draft) => { draft.print.paperSize = event.target.value as "A4" | "A3"; }, "Format d’impression modifié")}><option>A4</option><option>A3</option></select></label><label className="text-sm font-medium">Orientation<select className={`${inputClass} mt-1 w-40`} value={settings.print.orientation} onChange={(event) => updateSettings((draft) => { draft.print.orientation = event.target.value as "portrait" | "landscape"; }, "Orientation d’impression modifiée")}><option value="portrait">Portrait</option><option value="landscape">Paysage</option></select></label></div><div className="grid gap-5 xl:grid-cols-[1fr_380px]"><div className="grid gap-2 sm:grid-cols-2">{columns.map((column, index) => <div className="flex items-center gap-2 rounded-lg border border-[var(--app-border)] p-2" key={column.id}><input type="checkbox" checked={column.visible} onChange={(event) => updateSettings((draft) => { const target = draft.print.columns.find((item) => item.id === column.id); if (target) target.visible = event.target.checked; }, "Colonne d’impression modifiée")} /><span className="flex-1 text-sm">{column.label}</span><button className={buttonClass} disabled={index === 0} onClick={() => reorderPrint(updateSettings, columns, index, -1)}>↑</button><button className={buttonClass} disabled={index === columns.length - 1} onClick={() => reorderPrint(updateSettings, columns, index, 1)}>↓</button></div>)}</div><div><p className="mb-2 text-sm font-semibold">Aperçu</p><div className={`mx-auto border border-slate-300 bg-white p-5 shadow-md ${settings.print.orientation === "landscape" ? "aspect-[1.414/1] w-full" : "aspect-[1/1.414] w-64"}`}><div className="mb-4 h-3 w-1/2 bg-slate-900" /><div className="grid grid-cols-3 gap-1">{columns.filter((item) => item.visible).slice(0, 12).map((item) => <div key={item.id} className="truncate border border-slate-200 bg-slate-50 p-1 text-[7px]">{item.label}</div>)}</div></div></div></div></SettingsPanel>;
}

function reorderPrint(updateSettings: ReturnType<typeof useSettings>["updateSettings"], columns: typeof import("@/features/settings/config/default-settings").defaultSettings.print.columns, index: number, direction: -1 | 1) { const next = index + direction; if (!columns[next]) return; const reordered = [...columns]; [reordered[index], reordered[next]] = [reordered[next], reordered[index]]; updateSettings((draft) => { draft.print.columns = reordered.map((item, order) => ({ ...item, order })); }, "Ordre des colonnes modifié"); }
