"use client";

import { useState } from "react";
import { useSettings } from "@/features/settings/components/SettingsProvider";
import { buttonClass, Field, inputClass, SettingsPanel } from "@/features/settings/components/SettingsUi";
import { createSettingsId } from "@/features/settings/services/settings-identifiers";
import type { CapacitySettings } from "@/features/settings/types/settings";

export function CapacitySettingsEditor() {
  const { settings, updateSettings } = useSettings();
  const [editing, setEditing] = useState<CapacitySettings | null>(null);
  const capacities = [...settings.production.capacities].sort((a, b) => a.order - b.order);
  function create() { setEditing({ id: "", label: "", active: true, order: capacities.length, scope: "department", targetId: settings.production.departments.find((item) => item.active)?.id ?? "", hoursPerDay: settings.production.planning.defaultCapacityHours, workingDays: [...settings.production.planning.workingDays], exceptions: [] }); }
  function save() { if (!editing?.label.trim() || !editing.targetId) return; const saved = { ...editing, id: editing.id || createSettingsId("capacity", editing.label, capacities.map((item) => item.id)) }; updateSettings((draft) => { const index = draft.production.capacities.findIndex((item) => item.id === saved.id); if (index >= 0) draft.production.capacities[index] = saved; else draft.production.capacities.push(saved); }, "Capacité mise à jour"); setEditing(null); }
  function reorder(index: number, direction: -1 | 1) { const target = index + direction; if (!capacities[target]) return; const next = [...capacities]; [next[index], next[target]] = [next[target], next[index]]; updateSettings((draft) => { draft.production.capacities = next.map((item, order) => ({ ...item, order })); }, "Ordre des capacités modifié"); }
  const targets = editing?.scope === "machine" ? settings.production.machines : settings.production.departments;
  return <SettingsPanel title="Capacités" description="Une capacité machine active est prioritaire sur la capacité par défaut de son département." actions={<button className={buttonClass} onClick={create}>Ajouter une capacité</button>}>
    <div className="space-y-2">{capacities.map((item, index) => <div key={item.id} className="flex flex-wrap items-center gap-2 rounded-lg border border-[var(--app-border)] p-3"><strong className="min-w-44 flex-1 text-sm">{item.label}</strong><span className="text-xs text-slate-500">{item.hoursPerDay.toLocaleString("fr-BE")} h/jour · {item.active ? "Active" : "Inactive"}</span><button className={buttonClass} disabled={index === 0} onClick={() => reorder(index, -1)}>↑</button><button className={buttonClass} disabled={index === capacities.length - 1} onClick={() => reorder(index, 1)}>↓</button><button className={buttonClass} onClick={() => setEditing(structuredClone(item))}>Modifier</button><button className={buttonClass} onClick={() => updateSettings((draft) => { draft.production.capacities = draft.production.capacities.filter((entry) => entry.id !== item.id); }, "Capacité supprimée")}>Supprimer</button></div>)}</div>
    {editing ? <div className="mt-4 grid gap-4 rounded-xl border border-[var(--app-border)] bg-slate-50 p-4 md:grid-cols-2"><Field label="Libellé"><input className={inputClass} value={editing.label} onChange={(event) => setEditing({ ...editing, label: event.target.value })} /></Field><Field label="Portée"><select className={inputClass} value={editing.scope} onChange={(event) => { const scope = event.target.value as CapacitySettings["scope"]; const firstTarget = scope === "machine" ? settings.production.machines[0]?.id : settings.production.departments[0]?.id; setEditing({ ...editing, scope, targetId: firstTarget ?? "" }); }}><option value="department">Département</option><option value="machine">Machine</option></select></Field><Field label="Cible"><select className={inputClass} value={editing.targetId} onChange={(event) => setEditing({ ...editing, targetId: event.target.value })}>{targets.map((target) => <option key={target.id} value={target.id}>{"displayName" in target ? target.displayName : target.label}</option>)}</select></Field><Field label="Heures par jour"><input type="number" min="0" step="0.5" className={inputClass} value={editing.hoursPerDay} onChange={(event) => setEditing({ ...editing, hoursPerDay: Number(event.target.value) })} /></Field><Field label="Jours travaillés (0=dimanche à 6=samedi)"><input className={inputClass} value={editing.workingDays.join(",")} onChange={(event) => setEditing({ ...editing, workingDays: parseDays(event.target.value) })} /></Field><Field label="Capacités exceptionnelles (AAAA-MM-JJ|heures)"><textarea className={`${inputClass} min-h-24 py-2`} value={editing.exceptions.map((item) => `${item.date}|${item.hours}`).join("\n")} onChange={(event) => setEditing({ ...editing, exceptions: parseExceptions(event.target.value) })} /></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={editing.active} onChange={(event) => setEditing({ ...editing, active: event.target.checked })} /> Capacité active</label><div className="flex gap-2 md:col-span-2"><button className={buttonClass} onClick={save}>Enregistrer</button><button className={buttonClass} onClick={() => setEditing(null)}>Annuler</button></div></div> : null}
  </SettingsPanel>;
}

function parseDays(value: string): number[] { return [...new Set(value.split(",").map(Number).filter((day) => Number.isInteger(day) && day >= 0 && day <= 6))]; }
function parseExceptions(value: string): CapacitySettings["exceptions"] { return value.split("\n").flatMap((line) => { const [date, rawHours] = line.split("|").map((item) => item.trim()); const hours = Number(rawHours); return /^\d{4}-\d{2}-\d{2}$/.test(date) && Number.isFinite(hours) ? [{ date, hours }] : []; }); }
