"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { enumerateMicrophones, startMicrophoneTest, type MicrophoneDevice, type MicrophoneTestHandle } from "@/features/mail-assistant/services/microphone-diagnostic-service";
import { VOICE_SIGNAL_LABELS, classifyVoiceLevel, type VoiceSignalQuality } from "@/features/mail-assistant/config/voice-diagnostic-defaults";
import { inputClass } from "@/features/settings/components/SettingsUi";

export function MicrophoneDiagnosticPanel({ selectedDeviceId, durationSeconds, onDevice }: { selectedDeviceId: string; durationSeconds: number; onDevice: (id: string) => void }) {
  const handle = useRef<MicrophoneTestHandle | null>(null); const audioUrl = useRef<string | null>(null); const autoStop = useRef(0);
  const [devices, setDevices] = useState<MicrophoneDevice[]>([]); const [permission, setPermission] = useState<"prompt" | "granted" | "denied" | "unsupported">("prompt"); const [testing, setTesting] = useState(false); const [level, setLevel] = useState(0); const [peak, setPeak] = useState(0); const [elapsed, setElapsed] = useState(0); const [quality, setQuality] = useState<VoiceSignalQuality>("absent"); const [playback, setPlayback] = useState<string | null>(null); const [lastResult, setLastResult] = useState("Aucun test effectué"); const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async () => { try { setDevices(await enumerateMicrophones()); } catch { setError("Impossible d’actualiser les périphériques audio."); } }, []);
  const discard = useCallback(() => { if (audioUrl.current) URL.revokeObjectURL(audioUrl.current); audioUrl.current = null; setPlayback(null); }, []);
  const stop = useCallback(async () => { window.clearTimeout(autoStop.current); const current = handle.current; handle.current = null; if (!current) return; const result = await current.stop(); setTesting(false); setPeak(result.peak); setQuality(result.quality); setLastResult(`${VOICE_SIGNAL_LABELS[result.quality]} · ${new Intl.NumberFormat("fr-BE", { maximumFractionDigits: 1 }).format(result.durationSeconds)} s`); discard(); if (result.blob) { const url = URL.createObjectURL(result.blob); audioUrl.current = url; setPlayback(url); } await refresh(); }, [discard, refresh]);
  useEffect(() => { const initialRefresh = window.setTimeout(() => void refresh(), 0); return () => { window.clearTimeout(initialRefresh); window.clearTimeout(autoStop.current); void handle.current?.stop(); discard(); }; }, [discard, refresh]);
  async function test() { setError(null); discard(); try { const current = await startMicrophoneTest({ deviceId: selectedDeviceId, durationSeconds, onLevel(value, maximum, seconds) { setLevel(value); setPeak(maximum); setElapsed(seconds); setQuality(classifyVoiceLevel(maximum)); } }); handle.current = current; setPermission("granted"); setTesting(true); setElapsed(0); setPeak(0); autoStop.current = window.setTimeout(() => void stop(), durationSeconds * 1000); await refresh(); } catch (caught) { const name = caught instanceof DOMException ? caught.name : String(caught); const denied = name.includes("NotAllowed"); setPermission(denied ? "denied" : name.includes("unsupported") ? "unsupported" : "prompt"); setError(denied ? "Permission refusée. Dans Edge ou Chrome, autorisez le microphone depuis l’icône à gauche de l’adresse." : name.includes("NotReadable") ? "Le microphone semble occupé par une autre application." : "Navigateur non compatible ou microphone indisponible."); } }
  const permissionLabel = permission === "granted" ? "Microphone autorisé" : permission === "denied" ? "Permission refusée" : permission === "unsupported" ? "Navigateur non compatible" : "Permission non accordée";
  return <section aria-labelledby="microphone-test-title" className="rounded-2xl border border-slate-200 p-4"><h3 id="microphone-test-title" className="font-semibold text-slate-800">Test du microphone</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold text-slate-700">Microphone sélectionné<select className={`${inputClass} mt-1`} value={selectedDeviceId} onChange={(event) => onDevice(event.target.value)}><option value="">Microphone par défaut</option>{devices.map((device) => <option key={device.id || device.label} value={device.id}>{device.label}</option>)}</select></label><div className="text-sm text-slate-600"><p>{permissionLabel}</p><p>{devices.length ? `${devices.length} microphone(s) détecté(s)` : "Aucun microphone détecté ou noms masqués avant autorisation"}</p></div></div><div className="mt-4"><div role="meter" aria-label="Niveau d’entrée du microphone" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(level * 100)} aria-valuetext={VOICE_SIGNAL_LABELS[quality]} className="relative h-4 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-[#1f5f49] transition-[width] motion-reduce:transition-none" style={{ width: `${Math.min(100, level * 180)}%` }}/><span className="absolute inset-y-0 w-0.5 bg-slate-900" style={{ left: `${Math.min(100, peak * 180)}%` }}/></div><p aria-live="polite" className="mt-2 text-sm font-semibold">{VOICE_SIGNAL_LABELS[quality]} · pic {Math.round(peak * 100)} % · {elapsed.toFixed(1)} s</p></div><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={() => void test()} disabled={testing} className="rounded-xl bg-[#1f5f49] px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">Tester mon microphone</button><button type="button" onClick={() => void stop()} disabled={!testing} className="rounded-xl border px-4 py-3 text-sm font-semibold disabled:opacity-50">Arrêter le test</button>{playback ? <button type="button" onClick={() => { const audio = new Audio(playback); audio.onended = discard; void audio.play(); }} className="rounded-xl border px-4 py-3 text-sm font-semibold">Réécouter le test</button> : null}<button type="button" onClick={() => void refresh()} className="rounded-xl border px-4 py-3 text-sm font-semibold">Actualiser les périphériques</button></div><p className="mt-3 text-sm text-slate-600">Dernier résultat : {lastResult}. <span className="font-semibold">Vérifier les paramètres Windows du microphone</span>.</p>{error ? <p role="alert" className="mt-2 text-sm text-red-700">{error}</p> : null}</section>;
}
