/* Les aperçus locaux en data URL ne passent pas par l’optimiseur d’images. */
/* eslint-disable @next/next/no-img-element */
"use client";

import { useState } from "react";
import { useSettings } from "@/features/settings/components/SettingsProvider";
import { buttonClass, Field, inputClass, SettingsPanel } from "@/features/settings/components/SettingsUi";
import type { MachineSettings } from "@/features/settings/types/settings";

const blankMachine: MachineSettings = { id: "", active: true, name: "", displayName: "", department: "", machineType: "", photoDataUrl: "", technicalInformation: "" };

export function ProductionSettingsPanel() {
  const { settings, updateSettings } = useSettings();
  const [editing, setEditing] = useState<MachineSettings | null>(null);
  function saveMachine() { if (!editing?.id.trim() || !editing.name.trim()) return; updateSettings((draft) => { const index = draft.production.machines.findIndex((item) => item.id === editing.id); if (index >= 0) draft.production.machines[index] = editing; else draft.production.machines.push(editing); }, "Machine enregistrée"); setEditing(null); }
  function readPhoto(file?: File) { if (!file || !editing || !file.type.startsWith("image/")) return; const reader = new FileReader(); reader.onload = () => setEditing((current) => current ? { ...current, photoDataUrl: String(reader.result) } : current); reader.readAsDataURL(file); }
  return <div className="space-y-5"><SettingsPanel title="Machines" description="Gérez le référentiel local sans écrire dans l’ERP." actions={<button className={buttonClass} onClick={() => setEditing({ ...blankMachine })}>Ajouter une machine</button>}><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-[var(--app-border)] text-xs uppercase text-slate-500"><tr><th className="p-3">Active</th><th className="p-3">Identifiant</th><th className="p-3">Nom affiché</th><th className="p-3">Département</th><th className="p-3">Type</th><th className="p-3">Actions</th></tr></thead><tbody>{settings.production.machines.map((machine) => <tr key={machine.id} className="border-b border-slate-100"><td className="p-3">{machine.active ? "Oui" : "Non"}</td><td className="p-3 font-mono">{machine.id}</td><td className="p-3 font-medium">{machine.displayName}</td><td className="p-3">{machine.department}</td><td className="p-3">{machine.machineType}</td><td className="p-3"><div className="flex gap-2"><button className={buttonClass} onClick={() => setEditing({ ...machine })}>Modifier</button><button className={buttonClass} onClick={() => updateSettings((draft) => { draft.production.machines = draft.production.machines.filter((item) => item.id !== machine.id); }, "Machine supprimée")}>Supprimer</button></div></td></tr>)}</tbody></table></div></SettingsPanel>
  {editing && <SettingsPanel title={settings.production.machines.some((item) => item.id === editing.id) ? "Modifier la machine" : "Nouvelle machine"}><div className="grid gap-4 md:grid-cols-2"><Field label="Identifiant"><input className={inputClass} value={editing.id} disabled={settings.production.machines.some((item) => item.id === editing.id)} onChange={(event) => setEditing({ ...editing, id: event.target.value })} /></Field><Field label="Nom technique"><input className={inputClass} value={editing.name} onChange={(event) => setEditing({ ...editing, name: event.target.value })} /></Field><Field label="Nom affiché"><input className={inputClass} value={editing.displayName} onChange={(event) => setEditing({ ...editing, displayName: event.target.value })} /></Field><Field label="Département"><input className={inputClass} value={editing.department} onChange={(event) => setEditing({ ...editing, department: event.target.value })} /></Field><Field label="Type"><input className={inputClass} value={editing.machineType} onChange={(event) => setEditing({ ...editing, machineType: event.target.value })} /></Field><Field label="Photo"><input type="file" accept="image/*" className="block w-full text-sm" onChange={(event) => readPhoto(event.target.files?.[0])} /></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={editing.active} onChange={(event) => setEditing({ ...editing, active: event.target.checked })} /> Machine active</label><Field label="Informations techniques"><textarea className={`${inputClass} min-h-24 py-2`} value={editing.technicalInformation} onChange={(event) => setEditing({ ...editing, technicalInformation: event.target.value })} /></Field></div>{editing.photoDataUrl && <img src={editing.photoDataUrl} alt="Aperçu de la machine" className="mt-4 h-28 w-44 rounded-lg border border-[var(--app-border)] object-contain" />}<div className="mt-4 flex gap-2"><button className={buttonClass} onClick={saveMachine}>Enregistrer</button><button className={buttonClass} onClick={() => setEditing(null)}>Annuler</button></div></SettingsPanel>}
  <ReferenceLists /></div>;
}

function ReferenceLists() { const { settings, updateSettings } = useSettings(); const entries = [["departments", "Départements"], ["capacities", "Capacités"], ["priorities", "Priorités"], ["workOrderTypes", "Types d’OF"]] as const; return <SettingsPanel title="Référentiels de production" description="Une valeur par ligne."><div className="grid gap-4 md:grid-cols-2">{entries.map(([key, label]) => <Field key={key} label={label}><textarea className={`${inputClass} min-h-36 py-2`} value={settings.production[key].join("\n")} onChange={(event) => updateSettings((draft) => { draft.production[key] = event.target.value.split("\n").map((value) => value.trim()).filter(Boolean); }, `${label} mis à jour`)} /></Field>)}</div></SettingsPanel>; }
