"use client";

import { MailAssistantSpeechOutput } from "@/features/mail-assistant/components/MailAssistantSpeechOutput";
import type { MailAssistantStartSettings, MailOpeningBrief } from "@/features/mail-assistant/types/mail-assistant";
import { MailReasoningRecommendations } from "@/features/mail-reasoning/components/MailReasoningRecommendations";
import type { MailReasoningReport } from "@/features/mail-reasoning/types/mail-reasoning";

interface Props { firstName: string; account: string; brief: MailOpeningBrief | null; reasoning: MailReasoningReport | null; isLoading: boolean; error: string | null; settings: MailAssistantStartSettings; onStart: () => void }

export function MailCommandCenterStandby({ firstName, account, brief, reasoning, isLoading, error, settings, onStart }: Props) {
  const metrics = brief?.metrics;
  const counters = [[metrics?.unread ?? 0, "mails non lus"], [metrics?.totalPending ?? 0, "à traiter"], [metrics?.pendingReplies ?? 0, "à valider"], [metrics?.urgent ?? 0, "urgent"], [metrics?.preparedMeetings ?? 0, "réunions"], [(metrics?.followUpsDueToday ?? 0) + (metrics?.overdueFollowUps ?? 0), "relances"]] as const;
  const completed = [[Boolean(brief?.lastSyncAt), "Boîte locale synchronisée"], [Boolean(metrics?.processedTotal), `${metrics?.processedTotal ?? 0} mails déjà traités`], [Boolean(metrics?.noActionTotal), `${metrics?.noActionTotal ?? 0} mails classés sans action nécessaire`], [Boolean(metrics?.informational), `${metrics?.informational ?? 0} messages d’information classés`], [Boolean(metrics?.pendingDrafts), `${metrics?.pendingDrafts ?? 0} brouillons retrouvés`]].filter(([show]) => show);
  return <main className="min-h-[calc(100vh-4rem)] bg-[radial-gradient(circle_at_75%_10%,rgba(47,114,89,0.18),transparent_32%),#0b0e0d] px-5 py-14 text-[#f3f5f2]"><div className="mx-auto max-w-6xl">
    <div className="flex flex-wrap items-end justify-between gap-8"><div><p className="text-sm text-emerald-300/80">Bonjour {firstName}</p><h1 className="mt-3 text-5xl font-semibold tracking-[-0.055em] sm:text-7xl">Morning Brief</h1><p className="mt-4 text-sm text-white/45">{account} · {brief?.isLocalDataStale ? "Données locales à actualiser" : "Données locales récentes"}</p></div><button type="button" onClick={onStart} disabled={isLoading} className="min-h-12 rounded-full bg-[#d8f567] px-6 text-sm font-semibold text-[#11150f] transition hover:-translate-y-0.5 motion-reduce:transition-none disabled:opacity-50">{isLoading ? "Préparation…" : "Démarrer la session"}</button></div>
    {brief ? <div className="mt-6"><MailAssistantSpeechOutput text={brief.text} settings={settings} autoPlay={settings.speakOpeningBrief}/></div> : null}
    <section className="mt-16" aria-labelledby="overview-title"><h2 id="overview-title" className="text-xs font-semibold uppercase tracking-[0.22em] text-white/35">Situation du jour</h2><div className="mt-8 grid grid-cols-2 gap-x-8 gap-y-10 sm:grid-cols-3 lg:grid-cols-6">{counters.map(([value, label]) => <div key={label}><strong className="block text-5xl font-medium tracking-[-0.05em] sm:text-6xl">{value}</strong><span className="mt-2 block text-sm text-white/45">{label}</span></div>)}</div></section>
    <MailReasoningRecommendations report={reasoning}/>
    <div className="mt-24 grid gap-12 lg:grid-cols-[1fr_0.8fr]"><section><h2 className="text-xs font-semibold uppercase tracking-[0.22em] text-white/35">Travail déjà préparé</h2><div className="mt-5 space-y-3">{completed.length ? completed.map(([, label]) => <div key={String(label)} className="mail-session-enter flex items-center gap-4 rounded-2xl bg-white/[0.055] px-5 py-4"><span className="grid size-7 place-items-center rounded-full bg-emerald-300/15 text-emerald-300">✓</span><span className="font-medium">{label}</span></div>) : <p className="rounded-2xl bg-white/[0.04] p-5 text-white/45">Le contexte local est prêt. Aucune action sûre supplémentaire n’était nécessaire.</p>}</div></section><section><h2 className="text-xs font-semibold uppercase tracking-[0.22em] text-white/35">En attente de vous</h2><div className="mt-5 rounded-[1.75rem] bg-white/[0.07] p-6"><p className="text-2xl font-medium">{metrics?.totalPending ? `${metrics.totalPending} éléments demandent votre attention.` : "Rien ne bloque votre matinée."}</p><p className="mt-3 text-sm leading-6 text-white/45">{brief?.text ?? "Lecture de la mémoire locale…"}</p>{metrics?.pendingReplies ? <p className="mt-5 text-sm text-[#d8f567]">Je recommande de commencer par les réponses à valider.</p> : null}</div></section></div>
    {error ? <p role="alert" className="mt-8 text-sm text-amber-300">{error}</p> : null}<p className="mt-20 text-xs text-white/25">Travail local déterministe · aucun appel IA payant au démarrage · aucun envoi automatique</p>
  </div></main>;
}
