"use client";
import { useState } from "react";
import { MailAssistantSpeechOutput } from "@/features/mail-assistant/components/MailAssistantSpeechOutput";
import type { MailAssistantStartSettings, MailOpeningBrief } from "@/features/mail-assistant/types/mail-assistant";

export function MailSessionOpeningBrief({ brief, account, settings, onBegin, onVoiceFinished }: { brief: MailOpeningBrief; account: string; settings: MailAssistantStartSettings; onBegin: () => void; onVoiceFinished: () => void }) {
  const [detail, setDetail] = useState<"pending" | "new" | "status" | null>(null); const m = brief.metrics;
  const sync = brief.lastSyncAt ? new Intl.DateTimeFormat("fr-BE", { dateStyle: "short", timeStyle: "short" }).format(new Date(brief.lastSyncAt)) : "Jamais";
  return <div className="mx-auto max-w-3xl px-4 py-10 sm:px-6"><p className="text-sm font-semibold text-[#1f5f49]">Voici votre situation.</p><h1 className="mt-3 text-2xl font-semibold tracking-tight">Brief de démarrage</h1><p className="mt-2 text-sm text-slate-500">{account} · Dernière synchronisation : {sync} · Données locales {brief.isLocalDataStale ? "à actualiser" : "récentes"}</p><div className="mt-7 rounded-3xl border border-black/[0.06] bg-white p-6 shadow-[0_16px_50px_rgba(24,45,36,0.07)]"><p className="text-lg leading-8 text-slate-800">{brief.text}</p><div className="mt-5"><MailAssistantSpeechOutput text={brief.text} settings={settings} onFinished={onVoiceFinished}/></div></div><dl className="mt-6 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4">{[["Nouveaux", m.newMail], ["Réponses", m.pendingReplies], ["Brouillons", m.pendingDrafts], ["Sans statut", m.withoutStatus], ["Relances", m.followUpsDueToday + m.overdueFollowUps], ["Urgents", m.urgent]].map(([label, value]) => <div key={String(label)} className="rounded-2xl bg-black/[0.035] p-3"><dt className="text-slate-500">{label}</dt><dd className="mt-1 text-xl font-semibold">{value}</dd></div>)}</dl><div className="mt-7 flex flex-wrap gap-2"><button type="button" onClick={onBegin} className="min-h-11 rounded-xl bg-[#1f5f49] px-5 font-semibold text-white">Commencer</button><button type="button" onClick={() => setDetail("pending")} className="min-h-11 rounded-xl border px-4">Voir les éléments en attente</button><button type="button" onClick={() => setDetail("new")} className="min-h-11 rounded-xl border px-4">Voir les nouveaux mails</button><button type="button" onClick={() => setDetail("status")} className="min-h-11 rounded-xl border px-4">Voir les mails sans statut</button></div>{detail ? <p role="status" className="mt-4 rounded-xl bg-[#edf3ef] p-4 text-sm">{detail === "pending" ? `${m.totalPending} élément(s) en attente, dont ${m.pendingReplies} réponse(s) et ${m.pendingDrafts} brouillon(s).` : detail === "new" ? `${m.newMail} nouveau(x) mail(s), dont ${m.urgent} urgent(s).` : `${m.withoutStatus} mail(s) sans statut assistant.`}</p> : null}</div>;
}
