"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import type { MailAssistantStartSettings } from "@/features/mail-assistant/types/mail-assistant";
import { browserTtsProvider } from "@/features/mail-assistant/services/browser-tts-provider";

export function MailAssistantSpeechOutput({ text, settings, autoPlay = true, onFinished }: { text: string; settings: MailAssistantStartSettings; autoPlay?: boolean; onFinished?: () => void }) {
  const played = useRef("");
  const [state, setState] = useState<"off" | "speaking" | "paused" | "stopped" | "unsupported" | "error">("off");
  const speak = useCallback(() => { if (settings.ttsProvider !== "system-browser" || !browserTtsProvider.supported()) { setState("unsupported"); return; } browserTtsProvider.speak({ text, language: settings.preferredLanguage, voiceId: settings.preferredVoiceId, voiceName: settings.preferredVoiceName, rate: settings.speechRate, pitch: settings.speechPitch, volume: settings.speechVolume, onStart: () => setState("speaking"), onEnd: () => { setState("stopped"); onFinished?.(); }, onError: () => setState("error") }); }, [onFinished, settings.preferredLanguage, settings.preferredVoiceId, settings.preferredVoiceName, settings.speechPitch, settings.speechRate, settings.speechVolume, settings.ttsProvider, text]);
  useEffect(() => { if (autoPlay && settings.voiceOutputEnabled && played.current !== text) { played.current = text; speak(); } return () => browserTtsProvider.stop(); }, [autoPlay, settings.voiceOutputEnabled, speak, text]);
  if (!settings.voiceOutputEnabled) return null;
  if (state === "unsupported" || state === "error") return <div role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><p className="font-semibold">La synthèse vocale n’est pas disponible. La conversation continue en texte.</p><p className="mt-2 whitespace-pre-wrap text-slate-800">{text}</p></div>;
  return <div className="flex flex-wrap items-center gap-2 text-sm"><span role="status" className="font-semibold text-[var(--app-primary)]">{state === "speaking" ? "Assistant en train de parler…" : state === "paused" ? "Lecture en pause" : "Assistant silencieux"}</span>{state === "speaking" ? <button type="button" onClick={() => { browserTtsProvider.pause(); setState("paused"); }} className="rounded-lg border px-3 py-2">Pause</button> : state === "paused" ? <button type="button" onClick={() => { browserTtsProvider.resume(); setState("speaking"); }} className="rounded-lg border px-3 py-2">Reprendre</button> : null}<button type="button" onClick={() => { browserTtsProvider.stop(); setState("stopped"); }} className="rounded-lg border px-3 py-2">Arrêter</button>{settings.replayButtonVisible ? <button type="button" onClick={speak} className="rounded-lg border px-3 py-2">Écouter à nouveau</button> : null}</div>;
}
