import { MailReplyProposal } from "@/features/mail-assistant/components/MailReplyProposal";
import type { MailAssistantReplyProposal, MailAssistantSessionMessage } from "@/features/mail-assistant/types/mail-assistant";

export function MailDecisionCard({ message, reply, position, total, onCommand, onOpenOriginal }: { message: MailAssistantSessionMessage; reply?: MailAssistantReplyProposal; position: number; total: number; onCommand: (text: string) => void; onOpenOriginal: () => void }) {
  return <article className="mail-session-enter rounded-[1.6rem] border border-black/[0.07] bg-white p-5 shadow-[0_14px_50px_rgba(27,41,35,0.055)] sm:p-7">
    <div className="flex items-center justify-between gap-4"><span className="text-xs font-semibold text-slate-400">Mail {position} sur {total}</span>{message.classification.isUrgent ? <span className="rounded-full bg-red-50 px-2.5 py-1 text-xs font-semibold text-red-700">Urgent</span> : null}</div>
    <div className="mt-5"><p className="text-lg font-semibold">{message.from.name ?? message.from.email}</p><h3 className="mt-1 text-xl font-semibold tracking-[-0.02em]">{message.subject}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{message.summary || message.snippet}</p></div>
    <div className="mt-4 flex flex-wrap gap-x-5 gap-y-1 text-xs text-slate-400"><span>{message.classification.reason}</span>{reply?.detectedDeadline ? <span>Échéance · {reply.detectedDeadline}</span> : null}</div>
    {reply ? <MailReplyProposal reply={reply}/> : null}
    <div className="mt-5 flex flex-wrap items-center gap-2"><button type="button" onClick={() => onCommand(`Valide le mail ${message.sessionNumber}`)} className="min-h-11 rounded-xl bg-[#1f5f49] px-5 text-sm font-semibold text-white">Valider</button><button type="button" onClick={() => onCommand(`Fais le mail ${message.sessionNumber} plus diplomatique`)} className="min-h-11 rounded-xl border border-black/10 px-4 text-sm font-semibold">Modifier</button><button type="button" onClick={() => onCommand(`Ignore le mail ${message.sessionNumber}`)} className="min-h-11 rounded-xl px-3 text-sm font-medium text-slate-500">Ignorer</button><details className="relative ml-auto"><summary className="cursor-pointer rounded-xl px-3 py-2 text-sm font-semibold text-slate-500">Plus</summary><div className="absolute right-0 top-10 z-10 w-48 rounded-xl border border-black/10 bg-white p-1.5 shadow-xl"><button type="button" onClick={() => onCommand(`Fais le mail ${message.sessionNumber} plus court`)} className="block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-50">Plus court</button><button type="button" onClick={() => onCommand(`Fais le mail ${message.sessionNumber} plus direct`)} className="block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-50">Plus direct</button><button type="button" onClick={onOpenOriginal} className="block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-slate-50">Voir le message</button></div></details></div>
  </article>;
}
