"use client";

import Link from "next/link";
import { useState } from "react";
import { EmptyState, fieldClass, formatEuropeanDate, ModuleHeader, primaryButton, secondaryButton, StatusPill } from "@/components/ui/ModuleUi";
import { updateDemoData, useDemoData } from "@/features/demo/services/demo-repository";
import type { ActionStatus, Priority } from "@/features/demo/types/demo";

export function ActionDetail({ id }: { id: string }) {
  const data = useDemoData();
  const action = data.actions.find((item) => item.id === id);
  const [editing, setEditing] = useState(false);
  if (!action) return <EmptyState title="Action introuvable" description="Cette action n’existe plus dans les données de démonstration." />;
  function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); updateDemoData((draft) => { const target = draft.actions.find((item) => item.id === id); if (!target) return; target.title = String(form.get("title")); target.description = String(form.get("description")); target.responsible = String(form.get("responsible")); target.priority = String(form.get("priority")) as Priority; target.status = String(form.get("status")) as ActionStatus; target.dueDate = String(form.get("dueDate")); target.history.unshift({ id: crypto.randomUUID(), date: new Date().toISOString(), author: "Daniel Mülverstedt", description: "Action modifiée" }); }); setEditing(false); }
  return <div className="mx-auto max-w-5xl"><ModuleHeader eyebrow={action.id} title={action.title} description={action.description} actions={<><Link href="/actions" className={secondaryButton}>Retour</Link><button className={primaryButton} onClick={() => setEditing((value) => !value)}>{editing ? "Fermer" : "Modifier"}</button></>} />
    {editing ? <form onSubmit={save} className="mt-6 grid gap-3 rounded-2xl border border-[var(--app-border)] bg-white p-5 sm:grid-cols-2"><input name="title" defaultValue={action.title} required className={fieldClass} /><input name="responsible" defaultValue={action.responsible} required className={fieldClass} /><textarea name="description" defaultValue={action.description} required className={`${fieldClass} min-h-28 py-3 sm:col-span-2`} /><select name="priority" defaultValue={action.priority} className={fieldClass}>{["Basse", "Normale", "Haute", "Urgente", "Bloquante"].map((item) => <option key={item}>{item}</option>)}</select><select name="status" defaultValue={action.status} className={fieldClass}>{["Ouverte", "En cours", "Reportée", "Terminée"].map((item) => <option key={item}>{item}</option>)}</select><input name="dueDate" type="date" defaultValue={action.dueDate} className={fieldClass} /><button className={primaryButton}>Enregistrer</button></form> : null}
    <div className="mt-6 grid gap-5 lg:grid-cols-3"><section className="rounded-2xl border border-[var(--app-border)] bg-white p-5 lg:col-span-2"><h2 className="font-semibold">Informations</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><Info label="Responsable" value={action.responsible} /><Info label="Département" value={action.department} /><Info label="Priorité" value={<StatusPill tone={action.priority === "Bloquante" || action.priority === "Urgente" ? "danger" : "warning"}>{action.priority}</StatusPill>} /><Info label="Statut" value={action.status} /><Info label="Échéance" value={formatEuropeanDate(action.dueDate)} /><Info label="Création" value={formatEuropeanDate(action.createdAt)} /><Info label="Origine" value={`${action.sourceType}${action.sourceId ? ` · ${action.sourceId}` : ""}`} />{action.workOrderId ? <Info label="OF lié" value={<Link className="text-[var(--app-primary)] underline" href={`/of/${action.workOrderId}`}>{action.workOrderId}</Link>} /> : null}</dl><h3 className="mt-6 text-sm font-semibold">Commentaires</h3><ul className="mt-2 space-y-2 text-sm text-slate-600">{action.comments.length ? action.comments.map((item) => <li key={item} className="rounded-lg bg-slate-50 p-3">{item}</li>) : <li>Aucun commentaire.</li>}</ul></section><section className="rounded-2xl border border-[var(--app-border)] bg-white p-5"><h2 className="font-semibold">Historique</h2><ol className="mt-4 space-y-4 border-l border-slate-200 pl-4">{action.history.map((item) => <li key={item.id}><p className="text-sm font-medium">{item.description}</p><p className="mt-1 text-xs text-slate-500">{formatEuropeanDate(item.date, true)} · {item.author}</p></li>)}</ol></section></div>
  </div>;
}

function Info({ label, value }: { label: string; value: React.ReactNode }) { return <div><dt className="text-xs font-semibold uppercase text-slate-500">{label}</dt><dd className="mt-1">{value}</dd></div>; }
